[package]
name = "amqp-manager"
version = "0.7.0"
authors = ["Adrian Benavides"]
edition = "2018"
description = "Lapin wrapper that encapsulates the use of channels and provides some helpful methods"
repository = "https://github.com/adrianbenavides/amqp-manager"
keywords = ["lapin", "amqp"]
license = "MIT"

[dependencies]
lapin = { version = "=1.7", default-features = false, features = ["rustls"] }

[dev-dependencies]
dotenv = "0.15"
futures = "0.3"
once_cell = "1"
rand = "0.8"
serde = "1"
serde_json = "1"
tokio = { version = "=0.2", features = ["rt-threaded", "macros", "time"] }
tokio-amqp = { version = "=0.1", default-features = false }
