[package]
name = "amqp-manager"
version = "0.1.0"
authors = ["Adrian Benavides"]
edition = "2018"
description = "Lapin wrapper that encapsulates the use of connections/channels and provides some helpful methods"
repository = "https://github.com/adrianbenavides/amqp-manager"
keywords = ["lapin", "amqp"]
license = "MIT"

[dependencies]
bytes = "0.5"
lapin = { version = "1.4", default-features = false, features = ["rustls"] }
mobc-lapin = "0.5"
serde = "1"
serde_json = "1"

[dev-dependencies]
dotenv = "0.15.0"
futures = "0.3.5"
lazy_static = "1.4.0"
rand = "0.7.3"
tokio = { version = "0.2.22", features = ["rt-threaded", "macros", "time"] }
tokio-amqp = "0.1.3"
