[package]
name = "amqp-manager"
version = "0.5.1"
authors = ["Adrian Benavides"]
edition = "2018"
description = "Lapin wrapper that encapsulates the use of connections/channels and provides some helpful methods"
repository = "https://github.com/adrianbenavides/amqp-manager"
keywords = ["lapin", "amqp"]
license = "MIT"

[dependencies]
lapin = { version = "=1.6", default-features = false, features = ["rustls"] }
mobc = "=0.5"

[dev-dependencies]
dotenv = "0.15"
futures = "0.3"
lazy_static = "1.4"
rand = "=0.7"
serde = "=1"
serde_json = "=1"
tokio = { version = "=0.2", features = ["rt-threaded", "macros", "time"] }
tokio-amqp = { version = "=0.1.3", default-features = false }
