[package]
name = "amqp-manager"
version = "0.5.3"
authors = ["Adrian Benavides"]
edition = "2018"
description = "Lapin wrapper that encapsulates the use of connections/channels and provides some helpful methods"
repository = "https://github.com/adrianbenavides/amqp-manager"
keywords = ["lapin", "amqp"]
license = "MIT"

[dependencies]
lapin = { version = "=1.6", default-features = false, features = ["rustls"] }
mobc = ">=0.5.12"

[dev-dependencies]
dotenv = "0.15"
futures = "0.3"
mobc = "=0.7"
once_cell = "=1"
rand = "=0.8"
serde = "=1"
serde_json = "=1"
tokio = { version = "=1", features = ["rt", "macros", "time"] }
tokio-amqp = { version = "=1", default-features = false }
