[package]
name = "amqp-manager"
version = "0.3.0"
authors = ["Adrian Benavides"]
edition = "2018"
description = "Lapin wrapper that encapsulates the use of connections/channels and provides some helpful methods"
repository = "https://github.com/adrianbenavides/amqp-manager"
keywords = ["lapin", "amqp"]
license = "MIT"

[dependencies]
bytes = "1"
lapin = { version = "1", default-features = false, features = ["rustls"] }
mobc-lapin = "0.6"
serde = "1"
serde_json = "1"

[dev-dependencies]
dotenv = "0.15"
futures = "0.3"
lazy_static = "1.4"
rand = "0.8"
tokio = { version = "0.3.7", features = ["rt-multi-thread", "macros", "time"] }
tokio-amqp = "0.3"
